### ISSUE TITLE
Default development tool-chain

### ISSUE THREAD

**Issue by plankter** [BodenmillerGroup/cookiecutter-python#1]
I would add `black` code formatter (https://github.com/psf/black) into development dependencies. It is now part of Python Software Foundation and formatting rules are quite good. Otherwise we'll have a code style mess across different projects.

Also it makes sense to add a linter and a test framework by default as a dev dependencies. Something like `PyTest` and `flake8` / `pylint`. They are not always useful in Notebook scenarios, but it is a good idea to let people know about these tools as early as possible.

**Comment by jwindhager** [comment]
Good point. Personally, I use `black`, `flake8` and `pytest` for most of my projects, too.

However, in my opinion, this would only make sense if it integrates well with Jupyter notebooks, as data analysis using Jupyter notebooks is the primary purpose of this template. Do you know if this is the case?

**Comment by votti** [comment]
There is a black plugin for jupyter lab.
Also, if `jupytext` is used (which I would recommend), `black` can be run over the `.py` file.

**Comment by jwindhager** [comment]
Sounds great! Happy to take pull requests.
