### ISSUE TITLE
Pinning dependencies versions

### ISSUE THREAD

**Issue by plankter** [BodenmillerGroup/cookiecutter-python#2]
We discussed it in the past and i know there are different opinions regarding this topic, but taking into account recent Vito's experience with `matplotlib` package, i would certainly suggest to pin all package versions for reproducibility reasons.

**Comment by jwindhager** [comment]
I totally agree that the dependencies in the `environment.yml` file should all be pinned for reproducibility reasons. However, in my opinion, *new* projects should always start with the newest versions and the initial `environment.yml` is therefore largely unpinned. It is intended that the user overwrites the initial `environment.yml` with his own (all-pinned) environment export after initialization of the project. I will add this to the readme.

To clarify, The intention of having both an `environment.yml` file and a `requirements.txt` file is precisely to support both use cases. While the dependencies in the `environment.yml` should be pinned for reproducibility reasons, the dependencies in the `requirements.txt` should remain "as unpinned as possible" to allow for installation of the most up-to-date package.

Do you agree with this strategy?

**Comment by votti** [comment]
My take on this is:
- Only pin what is necessary -> you actually do not want to get stuck on old versions. Usually things improve over time, bugs get fixed and features get added - even if this means that you need to fix some code now and then.

- Print the conda environment used as part of the default notebook template:
```
!conda env export -p {sys.prefix}
```
-> This allows you to reproduce the exact environment used to run the notebook. Convenient if you add packages in the middle of the analysis and do not rerun all notebooks.

- Once you publish, make a copy of the environment.yml where everything is pinned.
Even better, create a singularity container from the conda environment and push it to some public repository.
Eg here an example how to create a singularity container form a conda:
https://github.com/votti/singularity-builds/tree/master/rinla

**Comment by jwindhager** [comment]
> * Only pin what is necessary -> you actually do not want to get stuck on old versions. Usually things improve over time, bugs get fixed and features get added - even if this means that you need to fix some code now and then.
> * Print the conda environment used as part of the default notebook template:
>
> -> This allows you to reproduce the exact environment used to run the notebook. Convenient if you add packages in the middle of the analysis and do not rerun all notebooks.

In principle, I like this strategy. However, this would require to version-control the output of the Jupyter notebooks, which is not recommended (and therefore disabled, see .gitignore template).

> * Once you publish, make a copy of the environment.yml where everything is pinned. Even better, create a singularity container from the conda environment and push it to some public repository.

This was the plan, see my comment above. I think using containerization would be to much to ask, but is certainly an option. Maybe good for an `advanced` branch of this template?

**Comment by votti** [comment]
I also dont think the containerization should be default. I think this would just be a good 'best practice' note for publishing such analyses.

**Comment by votti** [comment]
@Version Control of Notebooks: I opened a separate issue to discuss this (#3).
