### ISSUE TITLE
To commit or not commit executed notebooks

### ISSUE THREAD

**Issue by votti** [BodenmillerGroup/cookiecutter-python#3]
This is more a general discussion, triggered by a comment of @jwindhager  not to commit notebooks: Should one commit executed notebooks or not?

I usually really recommend version control of jupyter notebooks - even if this means that some commits can get big - in the end this is the fastest way to see how previous analysis results looked like and more important to have actual plots that documents why some conclusions were made and easily share this with collegues. Which is in my opinion the main point of having a 'notebook' (vs a classical script) for analyses.

However this only works nicely if something like `jupytext` is used to keep a python script with the code-only to track actual changes and perform merges.

**Comment by jwindhager** [comment]
My take on this: The way it is currently set up, jupytext is used to convert to %-format, and only `.py` files are committed (see e.g. the example .ipynb template). The output of Jupyter notebooks (`.ipynb` files) as well as the metadata contained in these notebooks *is considered data* and should therefore not be version-controlled by git. If one needs data (e.g. plots, notebook output, ...) from previous runs, this data should be explicitly stored in the `data` directory.

If version controlling data using git is really desired, the user can always manually remove the corresponding line from the `.gitignore` file. Closing this issue.

**Comment by jwindhager** [comment]
Reopening this issue after offline discussion with @votti. The choice of strategy should be outlined in the README (with all advantages & disadvantages) and instructions should be added how to enable Jupyter notebook (`.ipynb`) version controlling, with links to additional resources such as [nbdime](https://github.com/jupyter/nbdime).
